### ISSUE TITLE
依賴.net standard

### ISSUE THREAD

**Issue by linkinlu** [WeihanLi/WeihanLi.Npoi#110]
我项目是 .net framework4.6.2的    引用了还要依赖.net standard?

**Comment by WeihanLi** [comment]
嗯？没太明白
.NET Framework 4.6.2 是支持 netstandard2.0 的包的，详见： https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support

**Comment by WeihanLi** [comment]
没问题的话关掉了哈，有需要的话可以重新打开
