### ISSUE TITLE
Open an exist excel and then modify or write to excelFile

### ISSUE THREAD

**Issue by hansolehuang** [WeihanLi/WeihanLi.Npoi#142]
var excelFile = $"D:\\Scheme0.xls";

DataTable table = ExcelHelper.ToDataTable(excelFile);
NpoiExtensions.ToExcelFile(table, excelFile);

System.UnauthorizedAccessException
  HResult=0x80070005
  Message=对路径“D:\Scheme0.xls”的访问被拒绝。
  Source=mscorlib
  StackTrace:
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   在 System.IO.File.Create(String path)
   在 EagleEyeOS.Excel.NpoiExtensions.WriteToFile(IWorkbook workbook, String filePath) 在 D:\Work\Code\EagleEyeOS.Excel\src\EagleEyeOS.Excel\NpoiExtensions.cs 中: 第 1223 行
   在 EagleEyeOS.Excel.NpoiExtensions.ToExcelFile(DataTable dataTable, String excelPath, ExcelSetting excelSetting) 在 D:\Work\Code\EagleEyeOS.Excel\src\EagleEyeOS.Excel\NpoiExtensions.cs 中: 第 796 行
   在 EagleEyeOS.Excel.NpoiExtensions.ToExcelFile(DataTable dataTable, String excelPath) 在 D:\Work\Code\EagleEyeOS.Excel\src\EagleEyeOS.Excel\NpoiExtensions.cs 中: 第 740 行
   在 Demo.Form1.Form1_Load(Object sender, EventArgs e) 在 D:\Work\Code\EagleEyeOS.Excel\Demo\Form1.cs 中: 第 85 行
   在 System.Windows.Forms.Form.OnLoad(EventArgs e)
   在 System.Windows.Forms.Form.OnCreateControl()
   在 System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   在 System.Windows.Forms.Control.CreateControl()
   在 System.Windows.Forms.Control.WmShowWindow(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   在 System.Windows.Forms.Form.WmShowWindow(Message& m)
   在 System.Windows.Forms.Form.WndProc(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   在 System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

  此异常最初是在此调用堆栈中引发的: 
    System.IO.__Error.WinIOError(int, string)
    System.IO.FileStream.Init(string, System.IO.FileMode, System.IO.FileAccess, int, bool, System.IO.FileShare, int, System.IO.FileOptions, Microsoft.Win32.Win32Native.SECURITY_ATTRIBUTES, string, bool, bool, bool)
    System.IO.FileStream.FileStream(string, System.IO.FileMode, System.IO.FileAccess, System.IO.FileShare, int)
    System.IO.File.Create(string)
    EagleEyeOS.Excel.NpoiExtensions.WriteToFile(NPOI.SS.UserModel.IWorkbook, string) (位于 NpoiExtensions.cs 中)
    EagleEyeOS.Excel.NpoiExtensions.ToExcelFile(System.Data.DataTable, string, EagleEyeOS.Excel.Settings.ExcelSetting) (位于 NpoiExtensions.cs 中)
    EagleEyeOS.Excel.NpoiExtensions.ToExcelFile(System.Data.DataTable, string) (位于 NpoiExtensions.cs 中)
    Demo.Form1.Form1_Load(object, System.EventArgs) (位于 Form1.cs 中)
    System.Windows.Forms.Form.OnLoad(System.EventArgs)
    System.Windows.Forms.Form.OnCreateControl()
    ...
    [调用堆栈已截断]
![屏幕截图 2022-06-06 163028](https://user-images.githubusercontent.com/48704618/172125845-fa2bcbf7-1a95-4b6e-8359-ee5913a2b007.png)

**Comment by hansolehuang** [comment]
It seems only been happened in *.xls file, but not in *.xlsx file..................

**Comment by hansolehuang** [comment]
Sorry, finally i find the $"D:\Scheme0.xls" is a read only file, please close it.

**Comment by WeihanLi** [comment]
Thanks for the report, would look into this

**Comment by hansolehuang** [comment]
您好感谢您的来信，祝身体健康，万事如意。黄向修

**Comment by hansolehuang** [comment]
advicing add to ToExcelFile()

try
            {
                workbook.WriteToFile(excelPath);
            }
            catch (UnauthorizedAccessException)
            {
                FileAttributes attr = (new FileInfo(excelPath)).Attributes;
                Console.Write("UnAuthorizedAccessException: Unable to access file. ");
                if ((attr & FileAttributes.ReadOnly) > 0)
                    throw new Exception("ReadOnly File");
            }
            finally
            {
                if (workbook != null) workbook.Close();
            }

**Comment by WeihanLi** [comment]
Hi @hansolehuang , you can have a review and leave your comments on this #143 PR if you want

**Comment by WeihanLi** [comment]
A new version [2.3.0](https://www.nuget.org/packages/WeihanLi.Npoi/2.3.0) had been released

**Comment by hansolehuang** [comment]
您好感谢您的来信，祝身体健康，万事如意。黄向修
