### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by yesyeey** [WeihanLi/WeihanLi.Npoi#146]
1.版本：netframework4.5 ，weihanli.npoi 1.13.0  中文乱码
  2.var csvEntities = WeihanLi.Npoi.CsvHelper.ToEntityList<CsvEntity>("3.csv");
 3.![image](https://user-images.githubusercontent.com/17378448/183593847-185741bd-dc0c-4409-84e9-27bf1f2bcc3e.png)
3.麻烦指导下 谢谢。

**Comment by WeihanLi** [comment]
文件编码问题？有可以重现问题的文件示例吗?

**Comment by yesyeey** [comment]
有文件 我上传一个
[4.csv](https://github.com/WeihanLi/WeihanLi.Npoi/files/9288997/4.csv)

**Comment by WeihanLi** [comment]
文件编码是 GB2312, 默认的编码是 UTF-8，可以试一下指定编码

``` c#
CsvHelper.ToEntities<TempModel>(csvPath, new CsvOptions()
        {
            Encoding = Encoding.GetEncoding("gb2312")
        })
```

**Comment by WeihanLi** [comment]
刚测试了一下，现在读的时候没有用配置的 encoding 额，我晚上更新一个版本，抱歉抱歉

**Comment by yesyeey** [comment]
别，十分感谢。 祝发财多多

**Comment by WeihanLi** [comment]
我自己测试是可以的，测试代码如下：

```c#
using var httpClient = new HttpClient();
var bytes = await httpClient.GetByteArrayAsync(@"https://github.com/WeihanLi/WeihanLi.Npoi/files/9288997/4.csv");

// required for .NET Core
Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
var encoding = Encoding.GetEncoding("gb2312");
foreach (var model in CsvHelper.ToEntityList<TempModel>(bytes, new CsvOptions { Encoding = encoding }))
{
	Console.WriteLine(model);
}

record TempModel
{
	public string a { get; set; }
	public string b { get; set; }
	public string c { get; set; }
}
```

输出结果如下：

![image](https://user-images.githubusercontent.com/7604648/183690431-717c91f3-5515-4dd1-9ff2-cd5d0fef3f23.png)
