### ISSUE TITLE
How to make the column header bold

### ISSUE THREAD

**Issue by 107295472** [WeihanLi/WeihanLi.Npoi#153]

**Comment by WeihanLi** [comment]
There's an example, you could configure the `RowAction`/`CellAction`

https://github.com/WeihanLi/WeihanLi.Npoi/blob/a8f158c4e8c6c6bca8bf91c8dce4101bfaf18188/samples/DotNetCoreSample/Program.cs#L216-L229

hope it helpful

**Comment by 107295472** [comment]
Thanks
