### ISSUE TITLE
ToExcelFileByTemplate Export template error

### ISSUE THREAD

**Issue by 107295472** [WeihanLi/WeihanLi.Npoi#155]
firstMovedIndex, lastMovedIndex out of order

**Comment by WeihanLi** [comment]
Any details? Could you please share a minimal repro?

**Comment by 107295472** [comment]
![image](https://github.com/user-attachments/assets/3fd3cc46-ce91-4368-9876-9bf198bdfee5)
var nfile = waybillExcel.ToExcelBytesByTemplate("C://test.xlsx");

**Comment by WeihanLi** [comment]
So sorry I did not get the issue, could you please explain more and it would be better if you share me a minimal repro

**Comment by 107295472** [comment]
好了没问题了
