### ISSUE TITLE
导出的时候怎么设置多个sheet页？

### ISSUE THREAD

**Issue by Object-lws** [WeihanLi/WeihanLi.Npoi#157]
我通过设置sheetIndex属性发现并不能设置多个sheet页

 //获取数据
 var data = await _requestACLService.GetOrderCompletedDataStatisticsAsync(request.createStartTime, request.createEndTime);

 var orderStatis = new List<OrderStatisticDto>() { data.orderStatistic };
 var orderStatisSetting = FluentSettings.For<OrderStatisticDto>();
 orderStatisSetting.HasExcelSetting(settings => new ExcelSetting());
 orderStatisSetting.HasSheetSetting(config =>
 {
     config.AutoColumnWidthEnabled = true;
     config.SheetName = "第一个sheet页";
     config.RowAction = row =>
     {
         var style = row.Sheet.Workbook.CreateCellStyle();
         if (row.RowNum == 0)
         {
             style.Alignment = HorizontalAlignment.Center;
             var font = row.Sheet.Workbook.CreateFont();
             font.FontName = "JetBrains Mono";
             font.IsBold = true;
             font.FontHeight = 200;
             style.SetFont(font);
             row.Cells.ForEach(c => c.CellStyle = style);
         }
         style.WrapText = true;//设置为可以换行
         row.Cells.ForEach(c => c.CellStyle = style);
     };
 });
 orderStatisSetting.Property(_ => _.orderTotal).HasColumnTitle("sheet页1数据1").HasColumnIndex(0);
 orderStatisSetting.Property(_ => _.copiesNumberTotal).HasColumnTitle("sheet页1数据2").HasColumnIndex(0);
 orderStatisSetting.Property(_ => _.textCountTotal).HasColumnTitle("sheet页1数据3").HasColumnIndex(0);
 orderStatisSetting.Property(_ => _.intradayCompletedTotal).HasColumnTitle("sheet页1数据4").HasColumnIndex(0);

 var typeStatis = data.orderTypeStatistics;
 var typeStatisticSetting = FluentSettings.For<OrderTypeStatisticsDto>();
 typeStatisticSetting.HasExcelSetting(settings => new ExcelSetting());
 typeStatisticSetting.HasSheetSetting(config =>
 {
     config.AutoColumnWidthEnabled = true;
     config.SheetName = "第二个sheet页";
     config.RowAction = row =>
     {
         var style = row.Sheet.Workbook.CreateCellStyle();
         if (row.RowNum == 0)
         {
             style.Alignment = HorizontalAlignment.Center;
             var font = row.Sheet.Workbook.CreateFont();
             font.FontName = "JetBrains Mono";
             font.IsBold = true;
             font.FontHeight = 200;
             style.SetFont(font);
             row.Cells.ForEach(c => c.CellStyle = style);
         }
         style.WrapText = true;//设置为可以换行
         row.Cells.ForEach(c => c.CellStyle = style);
     };
 },1);

 typeStatisticSetting.Property(_ => _.typeName).HasColumnTitle("sheet页2数据1").HasColumnIndex(0);
 typeStatisticSetting.Property(_ => _.orderTotal).HasColumnTitle("sheet页2数据2").HasColumnIndex(0);
 typeStatisticSetting.Property(_ => _.textCountTotal).HasColumnTitle("sheet页2数据3").HasColumnIndex(0);

 using var ms = new MemoryStream();
 orderStatis.ToExcelStream(ms, ExcelFormat.Xlsx);
 typeStatis.ToExcelStream(ms, ExcelFormat.Xlsx,1);

**Comment by WeihanLi** [comment]
想要导出到一个 excel 不同的 sheet 时，应该先准备一个 workbook 再把数据写到这个 workbook 的不同 sheet，最后把 workbook 写入到 stream 中

加了一个示例，可以作为一个参考：

https://github.com/WeihanLi/WeihanLi.Npoi/blob/d23e376d66e02e336f22e75270fb5a46c4c2c01c/samples/DotNetCoreSample/Program.cs#L17-L60

当前的 API 可能不太好用，有什么改进的建议也欢迎提出来，感觉可以添加一个方法直接基于 workbook 导入，这样就不需要用户显式创建 sheet 了

**Comment by WeihanLi** [comment]
> 感觉可以添加一个方法直接基于 workbook 导入，这样就不需要用户显式创建 sheet 了

这个方法已经有了，更新了下示例

https://github.com/WeihanLi/WeihanLi.Npoi/blob/44808b29a429a553365c367426b269786b30f75c/samples/DotNetCoreSample/Program.cs#L19-L56

**Comment by Object-lws** [comment]
这种方式固然可以，但没办法去自定义列名，想自定义列名还需再写其他方法或用我之前那种写法，你有什么好的建议吗

**Comment by WeihanLi** [comment]
写了一篇文档，希望有帮助
https://weihanli.github.io/WeihanLi.Npoi/articles/zh/MultiSheets.html

**Comment by Object-lws** [comment]
谢谢
