### ISSUE TITLE
怎么默认列顺序呢

### ISSUE THREAD

**Issue by 107295472** [WeihanLi/WeihanLi.Npoi#158]
[Column("状态", Index = 1)]
[Column("状态", Index = 2)]
[Column("状态", Index = 3)]

现在如果要在1后面插入一个，下面的inde全要改，太麻烦了，可以1后面写一个，下面就顺序串行吗

**Comment by WeihanLi** [comment]
是想最前面的定义 index 后面的按索性定义的顺序自行 + 1 自己排序是吗？
目前没有比较好的办法，我再试下看看 👀

**Comment by WeihanLi** [comment]
改了一个 3.0.0 的 preview 版本，默认使用 property 定义的顺序，也可以使用自定义的 property 排序，可以参考： 
- https://github.com/WeihanLi/WeihanLi.Npoi/blob/12c085d327147aa194749b5da959df830baa72e5/test/WeihanLi.Npoi.Test/ExcelTest.cs#L1209
- https://github.com/WeihanLi/WeihanLi.Npoi/blob/12c085d327147aa194749b5da959df830baa72e5/test/WeihanLi.Npoi.Test/ExcelTest.cs#L1277-L1289

可以试试看能不能满足需求哈，有什么别的想法也欢迎反馈哈

**Comment by 107295472** [comment]
谢谢，已升级好用，以前不用写index了，调整class顺序就好了
