### ISSUE TITLE
This source codes copy from FluentExcel?

### ISSUE THREAD

**Issue by xyting** [WeihanLi/WeihanLi.Npoi#23]
Many many codes copy from [FluentExcel](https://github.com/Arch/FluentExcel), please add the copyright info.

AND THE ATTRIBUTE FEATURE HAD BEED REMOVED IN `FluentExcel`

**Comment by WeihanLi** [comment]
Please point out where's copied in the code

**Comment by WeihanLi** [comment]
Add reference for FluentExcel in ReadMe.md and the docs, thanks for your working on FluentExcel.

Close the issue for now. If there's any code copied from FluentExcel project you find, please let me know and I'll remove it.

**Comment by xyting** [comment]
OK, I SEE

Also thanks your Good working on OSS.
