### ISSUE TITLE
Attributes.Sheet(StartRowIndex = 0)  dont work

### ISSUE THREAD

**Issue by joylin1984** [WeihanLi/WeihanLi.Npoi#26]
net 4.5.2   WeihanLi.Npoi 1.3.7

Codes for test:
 
``` C#
    [WeihanLi.Npoi.Attributes.Sheet(StartRowIndex = 0)]
    internal class MyClass
    {
        [WeihanLi.Npoi.Attributes.Column(Index = 0)]
        public int id { get; set; }

        [WeihanLi.Npoi.Attributes.Column(Index = 1)]
        public string Name { get; set; }

        [WeihanLi.Npoi.Attributes.Column(Index = 2)]
        public double pp { get; set; }

        [WeihanLi.Npoi.Attributes.Column(Index = 3)]
        public DateTime year { get; set; } = DateTime.Now;
    }
```
```C#
            var res = ExcelHelper.ToEntityList<MyClass>("test1.xlsx", 0);
            foreach (var r in res)
            {
                Console.WriteLine($"{r.id}---{r.Name}---{r.pp}---{r.year}");
            }
```
Exception:
`System.InvalidOperationException: Cannot get a text value from a numeric cell`

[test1.xlsx](https://github.com/WeihanLi/WeihanLi.Npoi/files/3462228/test1.xlsx)

**Comment by joylin1984** [comment]
额，看了源码，HeaderRowIndex 最少为0，也就是必须要有行头~~~

**Comment by WeihanLi** [comment]
It should be fixed with #27 , please try [1.3.8](https://www.nuget.org/packages/WeihanLi.Npoi/1.3.8)

你可以用一下 1.3.8 版本的包试一下，我本地测试的是可以了，如果还有问题欢迎反馈

![image](https://user-images.githubusercontent.com/7604648/62405501-7d359780-b5d0-11e9-9885-cb879613a6fb.png)

**Comment by joylin1984** [comment]
nice, 1.3.8 version is  work

**Comment by WeihanLi** [comment]
OK, thanks for the info
