### ISSUE TITLE
`ColumnAttribute` 能不能支持设置列宽

### ISSUE THREAD

**Issue by DaneSpiritGOD** [WeihanLi/WeihanLi.Npoi#30]
我现在又几列存放的是 json字符串，这个很长，且里面没有换行符，导致导出的Excel那列很宽，比较丑……

我看了下代码，
![image](https://user-images.githubusercontent.com/4377454/65208125-a483ed80-dac6-11e9-9ece-938d3125619e.png)
使用了自动列宽

感谢~

**Comment by WeihanLi** [comment]
对的，现在是自动列宽，实现自定义借款的话，应该没有什么问题，我回头试一下，加一下

**Comment by DaneSpiritGOD** [comment]
感谢。
其实之前使用 ExcelReport 导出Excel，但是它不支持Attribute标注，导致要写额外的代码，个人感觉不是很方便。
我觉得你的这个项目如果能支持像它那样，导出数据到模版文件，使用的人会增加不少。

**Comment by WeihanLi** [comment]
@DaneSpiritGOD  感谢你的建议，现在还不支持根据指定模板导出，我会考虑一下看怎么实现比较方便

1.4.0  版本已经支持列宽的设置，你可以通过Attribute `[Column(Width=30)]` 或者 FluentAPI `HasColumnWidth(30)` 来设置，有问题欢迎反馈，我会尽可能快的回复

关于导出数据到模板文件，新建了一个 issue <https://github.com/WeihanLi/WeihanLi.Npoi/issues/33>

**Comment by DaneSpiritGOD** [comment]
> @DaneSpiritGOD 感谢你的建议，现在还不支持根据指定模板导出，我会考虑一下看怎么实现比较方便
> 
> 1.4.0 版本已经支持列宽的设置，你可以通过Attribute `[Column(Width=30)]` 或者 FluentAPI `HasColumnWidth(30)` 来设置，有问题欢迎反馈，我会尽可能快的回复
> 
> 关于导出数据到模板文件，新建了一个 issue #33

谢谢

**Comment by WeihanLi** [comment]
@DaneSpiritGOD 现在 1.8.x 版本已经支持根据指定模板导出了，可以参考示例项目或者这篇介绍 <https://www.cnblogs.com/weihanli/p/12238048.html>
