### ISSUE TITLE
Excel导出后再导入空指针异常

### ISSUE THREAD

**Issue by DaneSpiritGOD** [WeihanLi/WeihanLi.Npoi#35]
导出实体类，
如果实体对象的某个导出对象为null，string.Empty，则对应导出Excel的那个Cell值为null。

然后如果不修改这个Excel文件，再导入系统，会 出现空指针异常。
![image](https://user-images.githubusercontent.com/4377454/66699845-b3a03900-ed1c-11e9-94b6-afba99e8c2d6.png)
空指针在上面图中的红框部分
`item.GetCell(columnIndex2)`计算出的值为null

我没有看导出的源代码，但我估计如果某个数据为空，那个cell直接没有创建。

我现在的解决方法是在导出时，遍历所有实体，发现有空值或string.Empty的属性，赋值成`空格`，这样能规避上述的空指针问题。

还请作者了解一下。

**Comment by WeihanLi** [comment]
好的，我试试，感谢反馈

**Comment by WeihanLi** [comment]
在 1.4.1 版本中进行了修复，处理了 entity 为 null 的情况，可以试试 1.4.1 版本，如果还有问题欢迎随时反馈

**Comment by DaneSpiritGOD** [comment]
> 在 1.4.1 版本中进行了修复，处理了 entity 为 null 的情况，可以试试 1.4.1 版本，如果还有问题欢迎随时反馈

我看了一下commit内容，好像我们想的不一致，能加个联系方式吗？QQ：838652739

**Comment by WeihanLi** [comment]
> > 在 1.4.1 版本中进行了修复，处理了 entity 为 null 的情况，可以试试 1.4.1 版本，如果还有问题欢迎随时反馈
> 
> 我看了一下commit内容，好像我们想的不一致，能加个联系方式吗？QQ：838652739

已经加了，Q: 764314552

**Comment by DaneSpiritGOD** [comment]
> > > 在 1.4.1 版本中进行了修复，处理了 entity 为 null 的情况，可以试试 1.4.1 版本，如果还有问题欢迎随时反馈
> > 
> > 
> > 我看了一下commit内容，好像我们想的不一致，能加个联系方式吗？QQ：838652739
> 
> 已经加了，Q: 764314552

没有看到信息啊，我加你了
