### ISSUE TITLE
ExcelHelper.ToDataTable 报 Cannot get a text value from a numeric cell

### ISSUE THREAD

**Issue by zl33842901** [WeihanLi/WeihanLi.Npoi#47]
InvalidOperationException: Cannot get a text value from a numeric cell

DataTable dataTable=ExcelHelper.ToDataTable(saveFileName);

**Comment by WeihanLi** [comment]
Thanks for your feedback, I'll try to solve it as soon as possible.

**Comment by WeihanLi** [comment]
Could you please provide a demo to reproduce? Sorry that I can not reproduce this problem

**Comment by WeihanLi** [comment]
@zl33842901 能否提供一个可重现这个问题的简单示例？我这里测试的没有问题，

测试代码： <https://github.com/WeihanLi/WeihanLi.Npoi/blob/dev/samples/DotNetCoreSample/Program.cs#L64>
