### ISSUE TITLE
purpose of int return value in NpoiExtension methods

### ISSUE THREAD

**Issue by totano** [WeihanLi/WeihanLi.Npoi#64]
this gets me confused, looking at the code it is just a constant value of 1, examples just discard it.
Shouldn't void be more appropriate? Is there something I am missing?

**Comment by WeihanLi** [comment]
That means the method invokes succeed now, maybe some methods will change to return the rows count of the sheet, but for now, the return value is meaningless, you can just ignore the return value.

For now, return void is much better indeed. I'll consider that.
