### ISSUE TITLE
ToExcelFile 导出 文件格式xlsx，用excel打开会提示"发现xxx.xls中的部分内容有问题"

### ISSUE THREAD

**Issue by zhujinhu21** [WeihanLi/WeihanLi.Npoi#72]
如果文件格式写成xls 打开不会提示。用的DotNetCoreSample 测试也是这样

**Comment by WeihanLi** [comment]
确实有这个问题，这个是 `NPOI` 的问题，之前测试也有遇到过，不过之前觉得没太大影响，就一直也没想着处理

**Comment by tonyqus** [comment]
要看具体xlsx文件了，请把xlsx传上来

**Comment by WeihanLi** [comment]
> 要看具体xlsx文件了，请把xlsx传上来

感谢瞿总的回复，这里上传了一个有问题的 excel 文件
[test.xlsx](https://github.com/WeihanLi/WeihanLi.Npoi/files/4689976/test.xlsx)

打开之后会有这样的提示，选择 “是” 之后可以正常打开

![image](https://user-images.githubusercontent.com/7604648/83044063-44424400-a076-11ea-84c6-da90112bc17f.png)

![image](https://user-images.githubusercontent.com/7604648/83044209-76ec3c80-a076-11ea-91f9-e4ac55815542.png)

**Comment by WeihanLi** [comment]
fixed with 1.9.6
