### ISSUE TITLE
在导入数据的时候，是否可以新增一个参数，用于设定表头开始的行数？

### ISSUE THREAD

**Issue by crashsol** [WeihanLi/WeihanLi.Npoi#73]
在导入数据的时候，是否可以指定表头的行数，比如表格的表头第一行是一个标题合并行，需要从第二行开始，才是数据的表头（对应实体的类属性），从表头的下一行参才真实的数据？

**Comment by WeihanLi** [comment]
可以配置的，可以通过 FluentAPI `HasSheetConfiguration(0, "SystemSettingsList", 2, true)` 来配置或者 Attribute  `SheetAttribute(StartRowIndex=2)` 来配置，默认第一行是 header，从第二行开始是数据，headerRowIndex

``` csharp
var setting = FluentSettings.For<TestEntity>();
setting.HasSheetConfiguration(0, "SystemSettingsList", 2, true);
```

**Comment by crashsol** [comment]
好的，谢谢，我去看看文档
