### ISSUE TITLE
请问一下，导入的时候，是否可以根据某个字段进行过滤？

### ISSUE THREAD

**Issue by crashsol** [WeihanLi/WeihanLi.Npoi#79]
由于XLS不是很标准，在导入数据的时候，需要根据第一个字段，判断长度是否为符合要求，在进行数据转换，否则其他项数据为空或则类型不对，导致导入失败？
![image](https://user-images.githubusercontent.com/17925647/92553064-a83ef000-f294-11ea-8455-e134bd138dcf.png)

**Comment by crashsol** [comment]
看源码里面，Setting里面只提供了开始行数StartRowIndex，可否在新增一个配置EndRowIndex，表示读取XLS的结束行，这样，可以就可以只读取需要的行数就可以了

**Comment by WeihanLi** [comment]
目前暂不支持数据验证，我之前遇到这种问题一般是导入成一个 list 之后再通过 LINQ 过滤不符合条件的数据，类型不对的数据可以配置 `FluentAPI` 通过 `ColumnInputFormatter` 来配置转换

**Comment by crashsol** [comment]
> 目前暂不支持数据验证，我之前遇到这种问题一般是导入成一个 list 之后再通过 LINQ 过滤不符合条件的数据，类型不对的数据可以配置 `FluentAPI` 通过 `ColumnInputFormatter` 来配置转换

嗯，目前是用这个方法解决的，主要遇到很多表格，前面是表头，后面是表尾，中间是数据，能否给Setting加一个EndRowIndex，这样读取数据的时候，就只要标记范围内的数据？

**Comment by WeihanLi** [comment]
嗯，可以的，也可以提供一个委托，根据当前数据来判断是否已经结束，下个版本加一下

**Comment by WeihanLi** [comment]
发布了一个新版本，现在是预览版 `1.10.0-preview-20200912-144223`，你可以先试一下，没问题的话我再发布一个正式版
<https://www.nuget.org/packages/WeihanLi.Npoi/1.10.0-preview-20200912-144223>

- 增加了 `EndRowIndex` 最后一行（从0开始，会读取，包含在读取范围内）
- FluentAPI 增加了 `WithDataValidation` 可以一个委托验证数据是否合法，如果不合法就不返回，可以参考单元测试

**Comment by crashsol** [comment]
感谢大佬，完美解决问题，可以发版了，感谢感谢

**Comment by WeihanLi** [comment]
好的，感谢反馈

**Comment by WeihanLi** [comment]
新版本发布了， fixed by #81
