### ISSUE TITLE
关于项目命名

### ISSUE THREAD

**Issue by tonyqus** [WeihanLi/WeihanLi.Npoi#87]
我看到你在新版中已经增加了驱动层，适配EPPlus和NPOI。

我是建议你参考ExcelReport项目的命名，驱动层他用的是ExcelReport.Driver.EPPlus和ExcelReport.Driver.NPOI，如果我没有记错的话。其实我不建议你把一个项目的名字用自己的名字冠名，虽然早期来看能够提升你的个人名气，但其实后期并没有什么帮助，而且会让别人觉得这个库完全是个人作品，存在一定使用风险。开源项目更多的时候是看社区贡献，而不是个人贡献，虽然主要贡献者不干了，基本这项目也挂了。

**Comment by tonyqus** [comment]
当然改项目名其实是个大改动，建议一步一步来，包括repo的名字可能也要改，那工程有点巨大。

**Comment by WeihanLi** [comment]
感谢建议，想改来着，但是一直没有想到比较好的名字，而且现在我是申请了 nuget prefix，之前想改成 `Amazing.*`，但是 Amazing 太泛了，nuget prefix 没办法申请，所以后来暂时搁置了，我想等到重构新版本差不多之后再重命名
