### ISSUE TITLE
Excel导出超出65536行报错 Invalid row number (65536) outside allowable range (0..65535)

### ISSUE THREAD

**Issue by zilo555** [WeihanLi/WeihanLi.Npoi#94]
大佬
Excel导出超出65536行报错 Invalid row number (65536) outside allowable range (0..65535)
该怎么办，好像没有直接的方法可以自动分sheet的

**Comment by WeihanLi** [comment]
`xls` 一个 Sheet 最多支持 65535 行，如果数据要在一个 Sheet 中可以通过指定 `ExcelFormat.Xlsx` 来导出，可以参考单元测试
现在暂时没有支持自动分 Sheet 的，感觉自己去支持分 Sheet 的话可能会更容易控制一些，主要是按数据量分页到不同的 Sheet 中处理，因为很多人的需求可能是不同的，有的人希望自动拆分的 Sheet 不带列头，有的希望有列头，大家的需求不尽相同，如果确实需要的话，我想一下加一下

**Comment by WeihanLi** [comment]
发布了一个新版本，可以试一下 <https://www.nuget.org/packages/WeihanLi.Npoi/1.13.0-preview-20201110-055747>

**Comment by WeihanLi** [comment]
1.13.0 发布了，可以升级到这个版本

**Comment by zilo555** [comment]
感谢大佬
