### ISSUE TITLE
picture

### ISSUE THREAD

**Issue by ZeguangZhang94** [WeihanLi/WeihanLi.Npoi#99]
If there are pictures in Excel, how to convert them into Entity or List.

**Comment by WeihanLi** [comment]
Does not support for now, what type do want get image as? `byte[]` or `Stream` or other type?

**Comment by zhangze123** [comment]
byte[]

**Comment by WeihanLi** [comment]
Ok, thanks for the info, I'll try to implement this at my best as soon as possible

**Comment by zhangze123** [comment]
If completed, please reply me here，thank you

**Comment by WeihanLi** [comment]
Ok, will do

**Comment by WeihanLi** [comment]
A new preview release(`WeihanLi.Npoi 1.15.0-preview-20210228-054739`) had been published to nuget, you can try this <https://www.nuget.org/packages/WeihanLi.Npoi/1.15.0-preview-20210228-054739>

**Comment by zhangze123** [comment]
ok，thanks

**Comment by zhangze123** [comment]
I tried it and found no problem

**Comment by WeihanLi** [comment]
Ok, great thanks for your feedback, will publish stable release later

**Comment by WeihanLi** [comment]
fixed by #103 , please use 1.15.0
